export const EVENT_COLORS =  [
    'indigo',
    'deep-purple',
    'indigo darken-3',
    'deep-purple darken-3',
    'cyan darken-3',
    'cyan',
    'green',
    'orange',
    'blue ',
    'indigo lighten-3',
    'deep-purple lighten-3',
    'cyan lighten-3',
    ' green darken-3',
    'orange darken-3',
    'blue darken-3',
    'green lighten-3',
    'orange lighten-3',
    'blue lighten-3',
  ]
  