allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - sharp
  - unrs-resolver
