export * from './academic-config.schema'
export * from './activity.schema'
export * from './common.schema'
export * from './generation.schema'
export * from './preferences.schema'
export * from './profile.schema'
export * from './schedule.schema'
export * from './subject.schema'
