services:
  ssr-client:
    image: ${IMAGE_NAME}
    environment:
      HOST: ${NUXT_HOST}
      PORT: ${NUXT_PORT}
      BASE_URL: ${BASE_URL}
      NUXT_API_URL: ${NUXT_API_URL}
      NUXT_PUBLIC_GSI_CLIENT_ID: ${NUXT_PUBLIC_GSI_CLIENT_ID}
      NUXT_PUBLIC_GTAG_ID: ${NUXT_PUBLIC_GTAG_ID}
      NUXT_GSI_API_KEY: ${NUXT_PUBLIC_GSI_API_KEY}
      NUXT_PUBLIC_GSI_DISCOVERY_DOCS: ${NUXT_PUBLIC_GSI_DISCOVERY_DOCS}
      NUXT_PUBLIC_GSI_SCOPES: ${NUXT_PUBLIC_GSI_SCOPES}
      VIRTUAL_PORT: ${NUXT_PORT}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ssr-client.rule=Host(`${VIRTUAL_HOST}`)"
      - "traefik.http.routers.ssr-client.entrypoints=websecure"
      - "traefik.http.routers.ssr-client.tls.certresolver=le"
      - "traefik.http.services.ssr-client.loadbalancer.server.port=${NUXT_PORT}"
    ports:
      - ${NUXT_PORT}
    networks:
      - proxy
networks:
  letsencrypt:
    name: letsencrypt
    external: true
