version: '3.8'

services:
  ssr-client:
    image: ${IMAGE_NAME}
    environment:
      HOST: ${NUXT_ENV_HOST}
      PORT: ${NUXT_ENV_PORT}
      BASE_URL: ${BASE_URL}
      NUXT_ENV_API_URL: ${NUXT_ENV_API_URL}
      NUXT_ENV_GOOGLE_CLIENT_ID: ${NUXT_ENV_GOOGLE_CLIENT_ID}
      NUXT_ENV_GOOGLE_ANALYTICS_ID: ${NUXT_ENV_GOOGLE_ANALYTICS_ID}
      NUXT_ENV_GOOGLE_API_KEY: ${NUXT_ENV_GOOGLE_API_KEY}
      NUXT_ENV_GOOGLE_DISCOVERY_DOCS: ${NUXT_ENV_GOOGLE_DISCOVERY_DOCS}
      NUXT_ENV_GOOGLE_SCOPES: ${NUXT_ENV_GOOGLE_SCOPES}
      VIRTUAL_PORT: ${NUXT_ENV_PORT}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    ports:
      - ${NUXT_ENV_PORT}
    networks:
      - letsencrypt
networks:
  letsencrypt:
    external:
      name: letsencrypt
