version: '3.8'

services:
  api-server:
    image:  ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    environment:
      HOST: ${NUXT_ENV_HOST}
      PORT: ${NUXT_ENV_PORT}
      NUXT_ENV_API_URL: ${NUXT_ENV_API_URL}
      VIRTUAL_PORT: ${NUXT_ENV_PORT}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    ports:
      - ${NUXT_ENV_PORT}
    networks:
      - letsencrypt
networks:
  letsencrypt:
    external:
      name: letsencrypt
