services:
  ssr-client:
    image: ${IMAGE_NAME}
    environment:
      HOST: ${NUXT_HOST}
      PORT: ${NUXT_PORT}
      BASE_URL: ${BASE_URL}
      NUXT_PUBLIC_API_URL: ${NUXT_API_URL}
      NUXT_PUBLIC_GSI_CLIENT_ID: ${NUXT_PUBLIC_GSI_CLIENT_ID}
      NUXT_PUBLIC_GTAG_ID: ${NUXT_PUBLIC_GTAG_ID}
      NUXT_GSI_API_KEY: ${NUXT_PUBLIC_GSI_API_KEY}
      NUXT_PUBLIC_GSI_DISCOVERY_DOCS: ${NUXT_PUBLIC_GSI_DISCOVERY_DOCS}
      NUXT_PUBLIC_GSI_SCOPES: ${NUXT_PUBLIC_GSI_SCOPES}
      VIRTUAL_PORT: ${NUXT_PORT}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    stop_grace_period: 30s
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:${NUXT_PORT} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 0s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${PROJECT_NAME:-horext-app}-ssr-client.rule=Host(`${VIRTUAL_HOST}`)"
      - "traefik.http.routers.${PROJECT_NAME:-horext-app}-ssr-client.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME:-horext-app}-ssr-client.tls.certresolver=le"
      - "traefik.http.services.${PROJECT_NAME:-horext-app}-ssr-client.loadbalancer.server.port=${NUXT_PORT}"
      - "traefik.http.services.${PROJECT_NAME:-horext-app}-ssr-client.loadbalancer.healthcheck.path=/"
      - "traefik.http.services.${PROJECT_NAME:-horext-app}-ssr-client.loadbalancer.healthcheck.interval=5s"
      - "traefik.http.services.${PROJECT_NAME:-horext-app}-ssr-client.loadbalancer.healthcheck.timeout=3s"
    ports:
      - ${NUXT_PORT}
    networks:
      - proxy
      - horext-internal
networks:
  proxy:
    name: proxy
    external: true
  horext-internal:
    name: horext-internal
