version: '3.8'

services:
  ssr-client:
    image: ${IMAGE_NAME}
    environment:
      HOST: ${NUXT_HOST}
      PORT: ${NUXT_PORT}
      BASE_URL: ${BASE_URL}
      NUXT_API_URL: ${NUXT_API_URL}
      NNUXT_PUBLIC_GSI_CLIENT_ID: ${NNUXT_PUBLIC_GSI_CLIENT_ID}
      NUXT_PUBLIC_GTAG_ID: ${NUXT_PUBLIC_GTAG_ID}
      NNUXT_GSI_API_KEY: ${NNUXT_PUBLIC_GSI_API_KEY}
      NNUXT_PUBLIC_GSI_DISCOVERY_DOCS: ${NNUXT_PUBLIC_GSI_DISCOVERY_DOCS}
      NNUXT_PUBLIC_GSI_SCOPES: ${NNUXT_PUBLIC_GSI_SCOPES}
      VIRTUAL_PORT: ${NUXT_PORT}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    ports:
      - ${NUXT_PORT}
    networks:
      - letsencrypt
networks:
  letsencrypt:
    external:
      name: letsencrypt
