name: CI Pipeline

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    environment: ${{ inputs.environment }}
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm 8.x
        uses: pnpm/action-setup@v3
        with:
          version: 8.x
  
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
  
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test:unit
